# syntax=docker/dockerfile:1.7
FROM golang:1.24.5 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/finpay-api ./cmd/finpay-api

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/finpay-api /finpay-api
USER nonroot:nonroot
EXPOSE 8080 2112
ENTRYPOINT ["/finpay-api"]
