# syntax=docker/dockerfile:1.7
FROM golang:1.24.5 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/finpay-client ./cmd/finpay-client

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/finpay-client /finpay-client
USER nonroot:nonroot
ENTRYPOINT ["/finpay-client"]
